### ISSUE TITLE
GT-169 Loader crashes on empty message

### ISSUE THREAD

**Issue by tofu-rocketry** [apel/apel#304]
Message only contains a single blank line in each of body, empaid and signer.

```
2023-05-16 10:18:10,153 - loader - INFO - Loading message 002d46b5/6455067fc4ae50. ID =
2023-05-16 10:18:10,153 - loader - INFO - Loading message from
2023-05-16 10:18:10,153 - dbloader - ERROR - Unexpected exception. Traceback follows...
Traceback (most recent call last):
  File "/usr/bin/apeldbloader", line 117, in run_as_daemon
    loader.load_all_msgs()
  File "/usr/lib/python2.7/site-packages/apel/db/loader/loader.py", line 149, in load_all_msgs
    self.load_msg(msg_text, signer)
  File "/usr/lib/python2.7/site-packages/apel/db/loader/loader.py", line 205, in load_msg
    records = self._rf.create_records(msg_text)
  File "/usr/lib/python2.7/site-packages/apel/db/loader/record_factory.py", line 86, in create_records
    header = lines.pop(0)
IndexError: pop from empty list
2023-05-16 10:18:10,153 - dbloader - INFO - The loader will shutdown.
2023-05-16 10:18:10,153 - loader - INFO - The loader has shut down.
```

**Comment by gregcorbett** [comment]
A test case check if each of body, empaid and signer was empty would be good, as they might manifest in different ways.
