### ISSUE TITLE
Can't unload old records with HEPscore23 code

### ISSUE THREAD

**Issue by tofu-rocketry** [apel/apel#388]
When trying to unload old-style non-dict benchmark records during HEPscore testing, got the following error:

```
2024-10-14 14:12:33,465 - apel.db.unloader - INFO - Unloading all records from VNormalisedSuperSummaries.
Traceback (most recent call last):
  File "/root/apel/bin/dbunloader.py", line 174, in <module>
    msgs, recs = unloader.unload_all(table_name, send_ur)
  File "/root/apel/apel/db/unloader.py", line 118, in unload_all
    msgs, records = self._write_messages(record_type, table_name, query, car)
  File "/root/apel/apel/db/unloader.py", line 233, in _write_messages
    self._write_apel(batch)
  File "/root/apel/apel/db/unloader.py", line 287, in _write_apel
    buf.write('%%\n'.join( [ record.get_msg(self._withhold_dns) for record in records ] ))
  File "/root/apel/apel/db/records/record.py", line 270, in get_msg
    self._check_fields()
  File "/root/apel/apel/db/records/normalised_summary.py", line 83, in _check_fields
    Record._check_fields(self)
  File "/root/apel/apel/db/records/record.py", line 362, in _check_fields
    raise InvalidRecordException("Unexpected field " + key + " in message.")
apel.db.records.record.InvalidRecordException: Unexpected field ServiceLevelType in message.
```

**Comment by tofu-rocketry** [comment]
Seems to be because `"ServiceLevelType"` is in `_db_fields`, so gets extracted to the Python record object, but then isn't in the `_msg_fields`. So we need a way to skip this field in the message. (We still need it on the DB side as it is there in the DB.)

**Comment by tofu-rocketry** [comment]
It needed the definition of `_all_fields` changing for the normalised summary record. Pretty much every record type has it as the super set of all, msg, db and ignored, but this one had it limited to being just msg.

```diff
-        self._all_fields = self._msg_fields
+        self._all_fields = self._db_fields
```

Changing it doesn't change what goes into the message, as that's still controlled by the `_msg_fields` config, but it stops the checker thinking the field shouldn't be there in the Python object.
