### ISSUE TITLE
Cloud summariser and hanging connections?

### ISSUE THREAD

**Issue by tofu-rocketry** [apel/apel#392]
Cloud summariser sometimes complains about its temporary table already existing:

```# apelsummariser -d /root/iris/config/iris-cloud-db.cfg -c /root/iris/config/iris-cloud-summariser.cfg
Traceback (most recent call last):
  File "/usr/bin/apelsummariser", line 164, in <module>
    runprocess(options.db, options.config, options.log_config)
  File "/usr/bin/apelsummariser", line 120, in runprocess
    db.summarise_cloud()
  File "/usr/lib/python2.7/site-packages/apel/db/backends/mysql.py", line 395, in summarise_cloud
    c.callproc(self._summarise_vms_proc, ())
  File "/usr/lib64/python2.7/site-packages/MySQLdb/cursors.py", line 310, in callproc
    self._query(q)
  File "/usr/lib64/python2.7/site-packages/MySQLdb/cursors.py", line 354, in _query
    rowcount = self._do_query(q)
  File "/usr/lib64/python2.7/site-packages/MySQLdb/cursors.py", line 318, in _do_query
    db.query(q)
_mysql_exceptions.OperationalError: (1050, "Table 'tvmusagepermonth' already exists")
```

This might be due to the summariser not closing its DB connection properly and leaving a hanging connection (that still has the table), or not committing the change properly.

**Comment by tofu-rocketry** [comment]
We added this to the unit tests where hanging was causing issues. Maybe need something similar elsewhere in the code?

`self.apel_db.db.close()`
