### ISSUE TITLE
Handle loading issues with Galera Cluster better

### ISSUE THREAD

**Issue by tofu-rocketry** [apel/apel#401]
Some issue with the Galera Cluster leads to this error and the message getting rejected, but the loader should probably retry or just stop as it likely means there's an issue with the Cluster that needs resolving first.

```
2024-12-06 09:53:27,269 - loader - INFO - Message contains 21 Summary records
2024-12-06 09:53:37,271 - apel.db.backends.mysql - ERROR - Error loading records: (-1, 'error totally whack')
2024-12-06 09:53:37,271 - apel.db.backends.mysql - ERROR - Transaction will be rolled back.
2024-12-06 09:53:37,272 - loader - WARNING - Message rejected. Parsing unsuccessful: (-1, 'error totally whack')
2024-12-06 09:53:37,273 - loader - INFO - Message saved to reject queue as 0000001e/6752c9a142a6c5
```

Doing a search, this error seems to be of type `InterfaceError`, so we could try catching that.

**Comment by tofu-rocketry** [comment]
A different type of error if the DB fails:

```
2025-01-29 07:54:01,473 - apel.db.backends.mysql - ERROR - Error loading records: (2013, 'Lost connection to server during query')
2025-01-29 07:54:01,474 - apel.db.backends.mysql - ERROR - Transaction will be rolled back.
2025-01-29 07:54:01,474 - dbloader - ERROR - Unexpected exception. Traceback follows...
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/apel/db/backends/mysql.py", line 168, in load_records
    self.db.commit()
MySQLdb._exceptions.OperationalError: (2013, 'Lost connection to server during query')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/apeldbloader", line 126, in run_as_daemon
    loader.load_all_msgs()
  File "/usr/lib/python3.9/site-packages/apel/db/loader/loader.py", line 153, in load_all_msgs
    self.load_msg(msg_text, signer)
  File "/usr/lib/python3.9/site-packages/apel/db/loader/loader.py", line 231, in load_msg
    self._apeldb.load_records(records, source=signer)
  File "/usr/lib/python3.9/site-packages/apel/db/backends/mysql.py", line 172, in load_records
    self.db.rollback()
MySQLdb._exceptions.OperationalError: (2006, 'Server has gone away')
2025-01-29 07:54:01,477 - dbloader - INFO - The loader will shutdown.
2025-01-29 07:54:01,477 - loader - INFO - The loader has shut down.
2025-01-29 07:54:01,477 - dbloader - INFO - =======================
```

**Comment by tofu-rocketry** [comment]
And another issue from the DB outage:

```
2025-01-29 07:45:00,881 - loader - INFO - Message contains 1000 Job records
2025-01-29 07:45:11,040 - apel.db.backends.mysql - ERROR - Error loading records: (9001, 'Max connect timeout reached while reaching hostgroup 2 after 10156ms')
2025-01-29 07:45:11,041 - apel.db.backends.mysql - ERROR - Transaction will be rolled back.
2025-01-29 07:45:11,041 - loader - WARNING - Message rejected. Parsing unsuccessful: (9001, 'Max connect timeout reached while reaching hostgroup 2 after 10156ms')
2025-01-29 07:45:11,042 - loader - INFO - Message saved to reject queue as 00000000/6799dc870a6c90
```
